version: '2.0'

services:
  Httpd:
    image: centos_php70_httpd:0
    volumes:
      - ./code:/var/www/html
    ports:
      - 80:80
  Mysql:
    image: docker.io/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: apassword1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
